#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function, unicode_literals
import argparse
import sys

import cuteshop


parser = argparse.ArgumentParser(
    description='Manages depedencies for Qt project.',
)
parser.add_argument('-e', '--raise-exception', action='store_true')
namespace = parser.parse_args()

try:
    cuteshop.run()
except Exception as e:
    if namespace.raise_exception:
        raise
    else:
        print('[!] {exception}'.format(exception=e))
        sys.exit(1)
